---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCm3keYm3z8Fa+Oqkq6VXFRYYHea3Q8VwfuNCPAyYO9RCfj8CFz/rzITMpekae/QSB6DVmvitLuPmY+d2L6GrpEj+S4MnIPGVzBsA0V5DLa2wkUWvlFzSwtZnGRZLxnye4Wa4Y2u+filThWo6IcYb+Om/Uq0AENQBkeT5BgrEosHI2ibdzLJTOMUFZyvMwPP1LAMz///6lkfpaJ45l/qjtUavrfP+WKzF2exl0mfzDOq8SPdaPJ8ZsIH88BR5QxIHXB7rkqdZ3FxHfCwJAndvmcr9c42RfJcPLZdivZLmcpAzOgoLRyBVMbnYFbuIsImBJDrSqeIXpxZUxV6pbhGnvczPx9m7u4YIXK5DtNBgTfCKj4uGRC517xRhYV0BXXrhfZwgHadajcfS/JZJ/GQK78kGBAIPAOFKVt5GYljyCDY4hbnTgwSVjFVKJUsKEziN991vmoXltYUdBL7DZcY1pKuteXOse/za2oKr+DV2u6sSye2zsdNRNXoVPFr6VjLk7ZDGbNh1W+4Mdjg9aX6KrgSWIert+lZeoYP45l3UtVrZCWXuoAYQq/nlpdPoXwqhgNkNEOt2GPCnQj8UGod3O9OUCUsv/v/gQtahO/Hep4ffuLfmEkBsyEu6tAQNN9YdhvjBKD8vXffW42P4XvHaREvBkV32FJGl7DECFtx4sybJkLODPkm7VwEPhN9GIge4ROPq/sJcBuFMlhIgeEEQk=
  template:
    metadata:
      creationTimestamp: null
      name: my-db-secret
      namespace: default
